filebeat.inputs:
- type: docker
  containers.ids: '*'


output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOST}"]
output.file:
  enabled: false


filebeat.modules:
- module: system
  syslog:
    enabled: true
    var.paths: ["/tmp/log/syslog*"]
  # Authorization logs
  auth:
    enabled: true
    var.paths: ["/tmp/log/auth.log*"]

- module: auditd
  log:
    enabled: true
    var.paths: ["/tmp/log/audit/audit.log*"]


filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # only containers labeled with "co.elastic.logs/enabled: true" will be retrieved
      hints.default_config.enabled: false


processors:
- add_cloud_metadata: ~
- add_locale:
    format: offset
- add_docker_metadata: ~
- add_host_metadata:
    netinfo.enabled: true


filebeat.overwrite_pipelines: true
setup.dashboards.enabled: true
setup.template.enabled: true
setup.template.overwrite: true
setup.kibana:
  host: "${KIBANA_HOST}"


logging.to_stderr: true
logging.to_files: false
logging.level: info
