filebeat.inputs:
- type: docker
  containers.ids: '*'


output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOST}"]
output.file:
  enabled: false


filebeat.modules:
- module: system
  syslog:
    enabled: true
    var.paths: ["/tmp/log/syslog*"]
  # Authorization logs
  auth:
    enabled: true
    var.paths: ["/tmp/log/auth.log*"]

- module: auditd
  log:
    enabled: true
    var.paths: ["/tmp/log/audit/audit.log*"]

- module: traefik
  access:
    enabled: true


filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: false
      templates:
        # Traefik config
        - condition.contains:
            container.image.name: "traefik"
          config:
            - module: traefik
              access:
                input:
                  type: container
                  paths:
                    - "/var/lib/docker/containers/${data.docker.container.id}/${data.docker.container.id}-json.log"


processors:
- add_cloud_metadata: ~
- add_locale:
    format: offset
- add_docker_metadata: ~
- add_host_metadata:
    netinfo.enabled: true


filebeat.overwrite_pipelines: true
setup.dashboards.enabled: true
setup.template.enabled: true
setup.template.overwrite: true
setup.kibana:
  host: "${KIBANA_HOST}"


logging.to_stderr: true
logging.to_files: false
logging.level: info
