# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

# Reads the current Linux' syslog and authorization  as well as auditd logs
filebeat.modules:
- module: system
  syslog:
    enabled: true
    var.paths: ["/tmp/log/syslog*"]
  auth:
    enabled: true
    var.paths: ["/tmp/log/auth.log*"]
- module: auditd
  log:
    enabled: true
    var.paths: ["/tmp/log/audit/audit.log*"]

# Read logs from all Docker containers
filebeat.inputs:
- type: docker
  containers.ids: '*'

#========================== Filebeat autodiscover ==============================
# https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
filebeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
      # This URL also contains instructions on multi-line logs
      hints.enabled: true

#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Logstash output ===============================
output.logstash:
  hosts: ["${LOGSTASH_HOST}"]

#============================== Kibana Dashboards ==========================
setup.dashboards.enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}"
