version: "3.7"

# This stack exists solely to deploy the traefik overlay network, 
# so that other stacks (including traefik-app) can attach to it.

services:
  scratch:
    image: scratch
    networks:
      - network
    deploy:
      replicas: 0

networks:
  network:
    driver: overlay
    attachable: true
