version: "3.7"

services:
  radarr:
    image: linuxserver/radarr:latest
    networks:
      - overlay_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=007
    volumes:
      - "${HTPC_CONFIG_DIR}/radarr:/config"
      - "${HTPC_DOWNLOAD_DIR}/complete:/downloads"
      - "${HTPC_MOVIE_DIR}:/movies"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 1m
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.radarr.entrypoints=websecure
        - traefik.http.routers.radarr.rule=Host(`radarr.${HTPC_DOMAIN}`)
        - traefik.http.routers.radarr.tls=true
        - traefik.http.routers.radarr.middlewares=auth
        - traefik.http.services.radarr.loadbalancer.server.port=7878

networks:
  overlay_network:
    external: true
