version: "3.7"

services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    networks:
      - overlay_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${HTPC_CONFIG_DIR}/sabnzbd:/config"
      - "${HTPC_DOWNLOAD_DIR}/complete:/downloads"
      - "${HTPC_DOWNLOAD_DIR}/incomplete:/incomplete-downloads"
      - "${HTPC_DOWNLOAD_DIR}/watch:/watch"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 1m
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.sabnzbd.entrypoints=websecure
        - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${HTPC_DOMAIN}`)
        - traefik.http.routers.sabnzbd.tls=true
        - traefik.http.routers.sabnzbd.middlewares=auth
        - traefik.http.services.sabnzbd.loadbalancer.server.port=8080

networks:
  overlay_network:
    external: true
