version: "3.7"

services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CONFIG_DIR}/sabnzbd:/config"
      - "${DOWNLOAD_DIR}/complete:/downloads"
      - "${DOWNLOAD_DIR}/incomplete-downloads:/incomplete-downloads"
      - "${DOWNLOAD_DIR}/watch:/watch"
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.sabnzbd.entrypoints=websecure'
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.routers.sabnzbd.middlewares=auth
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080

networks:
  traefik:
    external: true
