version: "3.7"

services:
  sonarr:
    image: linuxserver/sonarr:latest
    networks:
      - overlay_network
    environment:
      - PUID=${PUID}
      - PGID=${GROUP_ID_DOWNLOADERS}
      - TZ=${TZ}
      - UMASK=007
    volumes:
      - "${HTPC_CONFIG_DIR}/sonarr:/config"
      - "${HTPC_DOWNLOAD_DIR}/complete:/downloads"
      - "${HTPC_SHOW_DIR}:/tv"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 1m
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.sonarr.entrypoints=websecure
        - traefik.http.routers.sonarr.rule=Host(`sonarr.${HTPC_DOMAIN}`)
        - traefik.http.routers.sonarr.tls=true
        - traefik.http.routers.sonarr.middlewares=auth
        - traefik.http.services.sonarr.loadbalancer.server.port=8989

networks:
  overlay_network:
    external: true
