# static configuration for traefik

http:
  routers:
    # global redirect to https
    redirs:
      rule: "hostregexp(`{host:.+}`)"
      entrypoints:
        - "web"
      middlewares:
        - "redirect-to-https"
      service: "noop"
  middlewares:
    auth:
      basicAuth:
        usersFile: "/etc/traefik/userlist.txt"
        # Enable SSO for Organizr - the username will be forwarded
        # See https://github.com/causefx/Organizr/issues/1215
        headerField: "X-Forwarded-User"
    # global redirect to https
    redirect-to-https:
      redirectScheme:
        scheme: "https"
  services:
    # noop service, the URL will be never called
    noop:
      loadBalancer:
        servers:
        - url: "http://127.0.0.1"
